# jobs:
#   call-workflow:
#     uses: yoav7000/Central-ci-cd/.github/workflows/non-prod-feature-branch-wf.yaml@main
#     with:
#       app_name: devops-project
#     secrets:
#       DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#       DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

name: Non production environments pipeline
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push
        run: echo  ${{ vars.DOCKERHUB_USERNAME }}/${{inputs.app_name}}:${{ github.sha }}
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{inputs.app_name}}:${{ github.sha }}
      